[env]
TERM = "xterm-256color"

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 10

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[keyboard]
bindings = [
{ key = "=", mods="Control | Shift", action = "IncreaseFontSize" },
{ key = "+", mods="Control | Shift", action = "IncreaseFontSize" },
{ key = "_", mods="Control | Shift", action = "DecreaseFontSize" }
]