general.import = [ "current_theme.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 10

[keyboard]
bindings = [
{ key = "=", mods="Control | Shift", action = "IncreaseFontSize" },
{ key = "+", mods="Control | Shift", action = "IncreaseFontSize" },
{ key = "_", mods="Control | Shift", action = "DecreaseFontSize" }
]