[font]
size = 10

[font.normal]
family = "Iosevka"
style = "Regular"

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[[keyboard.bindings]]
key = "Plus"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "DecreaseFontSize"
